variables:
  IMAGE_NAME: suipanwan/suipanwan.com
  IMAGE_TAG: latest

stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: docker:20.10.20
  services:
    - docker:20.10.20-dind
  variables:
      DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $DOCKERHUB_AC -p $DOCKERHUB_PW
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG
    - docker push $IMAGE_NAME:$IMAGE_TAG