variables:
  IMAGE_NAME: suipanwan/suipanwan.com
  IMAGE_TAG: latest

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

npm-install:
  stage: build
  image: node:19-alpine
  script:
    - npm ci --legacy-peer-deps
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 30 mins
    paths:
      - .npm/
      - node_modules/

npm-build:
  stage: build
  image: node:19-alpine
  needs:
    - npm-install
  script:
    - CI=false npm run build
  artifacts:
    paths:
      - out
    expire_in: 30 mins


build-job:       # This job runs in the build stage, which runs first.
  stage: build
  needs:
    - npm-build
  image: docker:20.10.20
  services:
    - docker:20.10.20-dind
  variables:
      DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $DOCKERHUB_AC -p $DOCKERHUB_PW
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy-job:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY root@159.89.117.185 "
      docker login -u $DOCKERHUB_AC -p $DOCKERHUB_PW &&
      docker ps -aq | xargs docker stop | xargs docker rm &&
      docker run -d -p 8080:80 $IMAGE_NAME:$IMAGE_TAG"